# Generated by Django 4.2.1 on 2023-06-21 12:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('CommunicationSkills', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('improvement', 'Improvement'), ('below', 'Below')], default='below', max_length=100)),
                ('TeamworkandCollaboration', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('improvement', 'Improvement'), ('below', 'Below')], default='below', max_length=100)),
                ('ProductivityandTimeManagement', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('improvement', 'Improvement'), ('below', 'Below')], default='below', max_length=100)),
                ('ProfessionalismandWorkEthic', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('improvement', 'Improvement'), ('below', 'Below')], default='below', max_length=100)),
                ('JobKnowledgeandSkills', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('improvement', 'Improvement'), ('below', 'Below')], default='below', max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('comments', models.CharField(max_length=100, null=True)),
                ('officername', models.CharField(max_length=20)),
                ('Position', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('lastdate', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('vacation', 'Vacation'), ('sick-family', 'Sick-Family'), ('sick-self', 'Sick-Self'), ('funeral', 'Funeral'), ('others', 'Others')], default='vacation', max_length=100)),
                ('enterreason', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='account/images')),
                ('username', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('emp_id', models.IntegerField(default=123)),
                ('dob', models.DateField(blank=True, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(default='btech', max_length=30)),
                ('education', models.CharField(default='btech', max_length=30)),
                ('experience', models.CharField(default='none', max_length=30)),
                ('details', models.CharField(default='none', max_length=30)),
                ('postal_code', models.IntegerField(default=12345)),
                ('research', models.TextField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('emp_id', models.IntegerField(default=1)),
                ('amount', models.IntegerField(default=10000)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('Time', models.TimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Syl_updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('section', models.CharField(max_length=30)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('units', models.CharField(max_length=30)),
                ('current', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Assign_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=30)),
                ('emp_id', models.IntegerField(default=123)),
                ('year', models.IntegerField(default=1)),
                ('section', models.IntegerField(default=0)),
                ('subject', models.CharField(max_length=30)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
