# Generated by Django 4.1.7 on 2023-03-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('enter_id', models.CharField(max_length=20)),
                ('startdate', models.DateField()),
                ('lastdate', models.DateField()),
                ('enterreason', models.CharField(max_length=100)),
                ('reason', models.CharField(choices=[('vacation', 'Vacation'), ('sick-family', 'Sick-Family'), ('sick-self', 'Sick-Self'), ('funeral', 'Funeral'), ('others', 'Others')], max_length=100)),
            ],
        ),
    ]
