# Generated by Django 4.2.1 on 2023-06-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_sub',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
