# Generated by Django 4.1.7 on 2023-04-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaves',
            old_name='enter_id',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='leaves',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='leaves',
            name='reason',
        ),
        migrations.AlterField(
            model_name='leaves',
            name='lastdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
