# Generated by Django 4.2.1 on 2023-06-21 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('a3', '0002_alter_assign_sub_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_sub',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
