# Generated by Django 4.1.7 on 2023-04-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0002_rename_enter_id_leaves_name_remove_leaves_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='reason',
            field=models.CharField(choices=[('vacation', 'Vacation'), ('sick-family', 'Sick-Family'), ('sick-self', 'Sick-Self'), ('funeral', 'Funeral'), ('others', 'Others')], default='vacation', max_length=100),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='enterreason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
