# Generated by Django 4.2.1 on 2023-06-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0003_alter_assign_sub_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Syl_updates',
        ),
    ]
