# Generated by Django 4.1.7 on 2023-04-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0003_leaves_reason_alter_leaves_enterreason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('employee_id', models.IntegerField(max_length=10)),
                ('amount', models.IntegerField(max_length=10)),
            ],
        ),
    ]
