# Generated by Django 4.1.7 on 2023-04-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0004_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='salary',
            name='emp_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='salary',
            name='amount',
            field=models.IntegerField(default=10000),
        ),
    ]
