# Generated by Django 4.2.1 on 2023-06-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0005_syl_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='syl_updates',
            name='year',
            field=models.IntegerField(default=2),
        ),
    ]
