# Generated by Django 4.1.7 on 2023-04-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0005_remove_salary_employee_id_salary_emp_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('emp_id', models.IntegerField()),
                ('dob', models.DateField()),
                ('mobile', models.IntegerField(default='0000000000')),
                ('address', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=10)),
                ('postal_code', models.IntegerField(default=12345)),
            ],
        ),
        migrations.AlterField(
            model_name='salary',
            name='amount',
            field=models.IntegerField(default='10000'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='emp_id',
            field=models.IntegerField(default='1'),
        ),
    ]
