# Generated by Django 4.1.7 on 2023-04-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0006_profile_alter_salary_amount_alter_salary_emp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='profile',
            name='emp_id',
            field=models.IntegerField(default='123'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.IntegerField(default='12345'),
        ),
    ]
