# Generated by Django 4.2.1 on 2023-06-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0007_remove_assign_sub_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
