# Generated by Django 4.1.7 on 2023-04-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0007_rename_name_profile_username_alter_profile_emp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='emp_id',
            field=models.IntegerField(default=123),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.IntegerField(default=12345),
        ),
        migrations.AlterField(
            model_name='salary',
            name='amount',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='salary',
            name='emp_id',
            field=models.IntegerField(default=1),
        ),
    ]
