# Generated by Django 4.1.7 on 2023-04-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0008_alter_profile_emp_id_alter_profile_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
