# Generated by Django 4.2.1 on 2023-06-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0009_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='enterreason',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
