# Generated by Django 4.1.7 on 2023-04-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0009_alter_profile_dob_alter_profile_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('emp_id', models.IntegerField(default=1)),
                ('branch', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('section', models.CharField(max_length=12)),
                ('subject', models.CharField(max_length=5)),
            ],
        ),
    ]
