# Generated by Django 4.2.1 on 2023-06-27 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('a3', '0010_alter_leaves_enterreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
