# Generated by Django 4.1.7 on 2023-04-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0010_assign_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_sub',
            name='subject',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='assign_sub',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
