# Generated by Django 4.1.7 on 2023-04-21 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0011_alter_assign_sub_subject_alter_assign_sub_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='assign_sub',
            name='branch',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='assign_sub',
            name='section',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='assign_sub',
            name='subject',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(max_length=30),
        ),
    ]
