# Generated by Django 4.2.1 on 2023-06-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0011_alter_leaves_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
