# Generated by Django 4.2.1 on 2023-07-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0012_alter_leaves_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='enterreason',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='details',
            field=models.CharField(blank=True, default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='research',
            field=models.TextField(blank=True, default='None'),
        ),
    ]
