# Generated by Django 4.1.7 on 2023-04-21 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0012_salary_date_alter_assign_sub_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='Time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
