# Generated by Django 4.2.1 on 2023-07-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0013_alter_leaves_enterreason_alter_profile_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='stream',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='details',
            field=models.CharField(blank=True, default='none', max_length=100),
        ),
    ]
