# Generated by Django 4.2.1 on 2023-06-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0015_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syl_updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('emp_id', models.IntegerField(default=1)),
                ('subject', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('section', models.CharField(max_length=30)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('units', models.CharField(max_length=30)),
                ('current', models.CharField(max_length=30)),
            ],
        ),
    ]
