# Generated by Django 4.2.1 on 2023-06-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0016_syl_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('dean', 'Dean'), ('HOD', 'HOD'), ('professor', 'Professor'), ('assistant professor', 'Assistant Professor')], default='None', max_length=100),
        ),
    ]
