# Generated by Django 4.2.1 on 2023-07-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0016_remove_profile_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='NONE', max_length=20),
        ),
    ]
