# Generated by Django 4.2.1 on 2023-07-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0018_profile_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
