# Generated by Django 4.2.1 on 2023-07-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0019_alter_profile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='stream',
        ),
    ]
