# Generated by Django 4.2.1 on 2023-06-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0019_remove_profile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
