# Generated by Django 4.2.1 on 2023-07-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0021_remove_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deaprtment',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
