# Generated by Django 4.2.1 on 2023-06-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0021_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='firstname',
            new_name='surname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastname',
        ),
        migrations.AddField(
            model_name='profile',
            name='details',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(default='btech', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='btech', max_length=30),
        ),
    ]
