# Generated by Django 4.2.1 on 2023-06-16 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0022_rename_firstname_profile_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign_sub',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
