# Generated by Django 4.1.7 on 2023-04-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_status',
            field=models.CharField(choices=[('hr', 'HR'), ('employee', 'Employee')], default='employee', max_length=32),
        ),
    ]
