# Generated by Django 4.2.1 on 2023-06-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('hr', 'HR'), ('employee', 'Employee')], default='none', max_length=32),
        ),
    ]
