# Generated by Django 4.2.1 on 2023-06-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_branch_user_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joining_letter',
            field=models.FileField(default='None', upload_to='account/images'),
        ),
    ]
