# Generated by Django 4.2.1 on 2023-06-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_joining_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joining_letter',
            field=models.ImageField(default='None', upload_to='account/images'),
        ),
    ]
