# Generated by Django 4.2.1 on 2023-07-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_joining_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('hod', 'Hod'), ('employee', 'Professor')], default='none', max_length=30),
        ),
    ]
