# Generated by Django 4.2.1 on 2023-07-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='stream',
            new_name='department',
        ),
    ]
